arraymultyply
guglielmi-s/dsy-fe-playground pull request #28
Opened 2021-12-20 15:14 UTC by sciuto-s

2021-12-20 15:25 UTC, proietti-s approved these changes
BRAVOH!

2021-12-21 14:32 UTC, guglielmi-s requested changes

2021-12-21 14:32 UTC, guglielmi-s commented on js/es-4-codingCh#4.mjs
> +}
come mai hai pushato questo file?

2021-12-21 14:32 UTC, guglielmi-s commented on js/es-2-arrayMultiply.mjs
> +  for (let i = 1; i <= b; i++) {
prova ad usare .map per ciclare l array usando l indice per capire quando fermarti. `map(element, index)`

2021-12-21 14:34 UTC, sciuto-s commented on js/es-4-codingCh#4.mjs
> +}
era lo stesso file su cui stavamo facendo esercitazione, me lo sarò portato dietro sorry

2021-12-22 09:34 UTC, guglielmi-s approved these changes

2022-09-08 09:04 UTC, closed without merging